# -*- coding: utf-8 -*-
"""Practice_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yHlzD97br7iKicVnzBQEB2MVpAJXJ76V
"""

import pandas as pd
import numpy as np

df = pd.read_csv("data for panda exercise.csv")
df

df.shape

df.columns

a = df.head(10)

b = df.tail(5)

pd.concat([a,b])

df[df.Grade=='A']

sum(df.Grade=='A')

df[df['Best of Quizzes'] > 5]

df[df.Mid>25].count()

df.iloc[5:6]

df[4:5]

df[df['Student Name']=='Muhammad Ghazali Farid']

df['Assignment 2'].iloc[3:18]

df['Total Sessional (50)'].iloc[[1,3,5,6,7]]

drop = df.dropna()
drop

df[['Student Name','Mid','Grade']][(df.Grade=='A')]

df[df['Student Name'].str.contains('Ali')]

# df({'Quiz 1': 5, 'Quiz 2': 5, 'Assignment 1': -5, 'Assignment 2': -5, 'Mid':df['Final (50)']*3/4, 
#     'Final (50)':df['Mid']*3/4}, inplace = True)

df['Status'] = df['Grade'].apply(lambda x: 'Fail' if x is 'F' else 'Pass')
df

df.rename(columns={'Total (100)':'Grand Total'}, inplace=True)
df

df['Best of Quizzes'] = df['Quiz 1'] + df['Quiz 2']
df

"""Chapter 8"""

age = [20,22,26,27,21,55,41,67]
bins = [15,25,35,45,55,70]
c = pd.cut(age, bins)
c

c.codes

marks = [65,75,65,80,91,53]
grades = [0,60,70,80,90,100]
bins = pd.cut(marks, grades)
bins

lst = np.array(['F', 'C', 'B', 'A', 'A+'])
bins.codes

lst[bins.codes]

data = [50, 120, 70, 80, 65, 75, 95, 99, 100, 102]
bpRange = [0, 60, 80, 90, 100, 120]

stress = pd.cut(data, bpRange)
stress

desease = np.array(['Low', 'Normal', 'Pre-Hyptertension', 'Grade 1 Hyptertension', 'Grade 2 Hyptertension'])
desease[stress.codes]

